name: ROS2 Jazzy Build Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: src/jsk_rviz_plugins

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          python3-pip \
          python3-colcon-common-extensions \
          python3-rosdep \
          python3-vcstool \
          build-essential \
          cmake \
          git

    - name: Initialize rosdep
      run: |
        if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
          rosdep init
        fi
        rosdep update

    - name: Install package dependencies
      run: |
        cd /github/workspace
        # Install ROS2 packages manually
        apt-get update && apt-get install -y \
          ros-jazzy-rviz2 \
          ros-jazzy-rviz-common \
          ros-jazzy-rviz-default-plugins \
          ros-jazzy-rviz-rendering \
          ros-jazzy-rviz-ogre-vendor \
          ros-jazzy-interactive-markers \
          python3-scipy \
          python3-sklearn || echo "Some packages not available"
        
        # Install remaining dependencies
        rosdep install --from-paths src/jsk_rviz_plugins --ignore-src -r -y \
          --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers jsk_gui_msgs jsk_recognition_utils jsk_tools view_controller_msgs people_msgs jsk_footstep_msgs jsk_hark_msgs jsk_recognition_msgs jsk_topic_tools posedetection_msgs jsk_data pr2_description urdfdom_py image_publisher joint_state_publisher" || \
          echo "Some dependencies could not be installed"

    - name: Source ROS2 environment
      run: |
        echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
        source /opt/ros/jazzy/setup.bash

    - name: Build packages
      run: |
        cd /github/workspace
        source /opt/ros/jazzy/setup.bash
        colcon build --packages-select jsk_rviz_plugins \
          --cmake-args -DCMAKE_BUILD_TYPE=Release \
          --event-handlers console_direct+

    - name: Run tests
      run: |
        cd /github/workspace
        source /opt/ros/jazzy/setup.bash
        source install/setup.bash
        colcon test --packages-select jsk_rviz_plugins \
          --event-handlers console_direct+

    - name: Test results
      run: |
        cd /github/workspace
        colcon test-result --verbose